import turtle
wisher = turtle.Turtle()
wisher.pensize(5)
screen = turtle.Screen()
screen.bgcolor('pink')

def birthday_wish():
    #H
    wisher.penup()
    wisher.goto(-700, 370)
    wisher.pendown()
    wisher.color('dark blue', 'blue')
    wisher.begin_fill()
    wisher.right(90)
    wisher.forward(200)
    wisher.left(90)
    wisher.forward(30)
    wisher.left(90)
    wisher.forward(90)
    wisher.right(90)
    wisher.forward(70)
    wisher.right(90)
    wisher.forward(90)
    wisher.left(90)
    wisher.forward(30)
    wisher.left(90)
    wisher.forward(200)
    wisher.left(90)
    wisher.forward(30)
    wisher.left(90)
    wisher.forward(90)
    wisher.right(90)
    wisher.forward(70)
    wisher.right(90)
    wisher.forward(90)
    wisher.left(90)
    wisher.forward(30)
    wisher.end_fill()


    #A
    wisher.penup()
    wisher.goto(-550, 170)
    wisher.pendown()
    wisher.begin_fill()
    wisher.right(115)
    wisher.forward(200)
    wisher.right(125)
    wisher.forward(200)
    wisher.right(115)
    wisher.forward(30)
    wisher.right(45)
    wisher.forward(30)
    wisher.left(42)
    wisher.forward(90)
    wisher.left(45)
    wisher.forward(30)
    wisher.right(45)
    wisher.forward(20)
    wisher.end_fill()

    wisher.penup()
    wisher.goto(-505, 215)
    wisher.pendown()
    wisher.color('dark blue', 'white')
    wisher.begin_fill()
    wisher.right(120)
    for x in range(3):
        wisher.forward(90)
        wisher.right(120)
    wisher.end_fill()

    #P
    wisher.penup()
    wisher.goto(-340, 195)
    wisher.pendown()
    wisher.color('dark blue', 'blue')
    wisher.begin_fill()
    wisher.left(25)
    wisher.forward(150)
    wisher.goto(-340, 195)
    wisher.right(90)
    wisher.forward(30)
    wisher.left(90)
    wisher.forward(50)
    wisher.right(90)
    wisher.circle(50, 210)
    wisher.end_fill()
    wisher.penup()
    wisher.goto(-305, 270)
    wisher.pendown()
    wisher.color('dark blue', 'white')
    wisher.begin_fill()
    wisher.right(190)
    wisher.circle(30, 145)
    wisher.end_fill()

    #P
    wisher.right(105)
    wisher.penup()
    wisher.goto(-250, 195)
    wisher.pendown()
    wisher.color('dark blue', 'blue')
    wisher.begin_fill()
    wisher.left(25)
    wisher.forward(150)
    wisher.goto(-250, 195)
    wisher.right(90)
    wisher.forward(30)
    wisher.left(90)
    wisher.forward(50)
    wisher.right(90)
    wisher.circle(50, 210)
    wisher.end_fill()
    wisher.penup()
    wisher.goto(-215, 270)
    wisher.pendown()
    wisher.color('dark blue', 'white')
    wisher.begin_fill()
    wisher.right(190)
    wisher.circle(30, 145)
    wisher.end_fill()

    #Y
    wisher.right(105)
    wisher.penup()
    wisher.goto(-120, 195)
    wisher.pendown()
    wisher.color('dark blue', 'blue')
    wisher.begin_fill()
    wisher.left(10)
    wisher.forward(75)
    wisher.left(90)
    wisher.forward(75)
    wisher.right(90)
    wisher.forward(30)
    wisher.right(90)
    wisher.forward(75)
    wisher.left(90)
    wisher.forward(75)
    wisher.right(90)
    wisher.forward(30)
    wisher.right(90)
    wisher.forward(200)
    wisher.end_fill()

    #B
    wisher.penup()
    wisher.goto(-700, 70)
    wisher.pendown()
    wisher.color('red', 'lime')
    wisher.begin_fill()
    wisher.left(30)
    wisher.forward(275)
    wisher.left(90)
    wisher.circle(75, 150)
    wisher.right(125)
    wisher.circle(75, 160)
    wisher.end_fill()
    wisher.penup()
    wisher.goto(-675, -30)
    wisher.pendown()
    wisher.right(160)
    wisher.color('red', 'white')
    wisher.begin_fill()
    wisher.circle(55, 130)
    wisher.left(115)
    wisher.forward(95)
    wisher.end_fill()
    wisher.penup()
    wisher.goto(-675, -80)
    wisher.pendown()
    wisher.right(160)
    wisher.left(160)
    wisher.begin_fill()
    wisher.forward(95)
    wisher.left(90)
    wisher.circle(45, 180)
    wisher.end_fill()


    #I
    wisher.right(90)
    wisher.penup()
    wisher.goto(-580, -200)
    wisher.pendown()
    wisher.color('red', 'lime')
    wisher.begin_fill()
    for x in range(2):
        wisher.forward(200)
        wisher.right(90)
        wisher.forward(30)
        wisher.right(90)
    wisher.end_fill()


    #R
    wisher.right(90)
    wisher.penup()
    wisher.goto(-520, -200)
    wisher.pendown()
    wisher.color('red', 'lime')
    wisher.begin_fill()
    wisher.forward(30)
    wisher.left(90)
    wisher.forward(100)
    wisher.right(135)
    wisher.forward(130)
    wisher.left(45)
    wisher.forward(30)
    wisher.left(135)
    wisher.forward(100)
    wisher.right(90)
    wisher.circle(100, 150)
    wisher.left(78)
    wisher.forward(250)
    wisher.end_fill()
    wisher.color('red', 'white')
    wisher.penup()
    wisher.goto(-510, -70)
    wisher.pendown()
    wisher.begin_fill()
    wisher.left(180)
    wisher.forward(80)
    wisher.penup()
    wisher.goto(-510, -70)
    wisher.pendown()
    wisher.right(90)
    wisher.forward(20)
    wisher.circle(35, 170)
    wisher.forward(25)
    wisher.end_fill()
    #T
    wisher.penup()
    wisher.goto(-350, -200)
    wisher.pendown()
    wisher.color('red', 'lime')
    wisher.begin_fill()
    wisher.right(90)
    wisher.forward(220)
    wisher.left(90)
    wisher.forward(100)
    wisher.right(90)
    wisher.forward(20)
    wisher.right(90)
    wisher.forward(220)
    wisher.right(90)
    wisher.forward(20)
    wisher.right(90)
    wisher.forward(100)
    wisher.left(90)
    wisher.forward(220)
    wisher.right(90)
    wisher.forward(20)
    wisher.end_fill()
    #H
    wisher.penup()
    wisher.goto(-150, -200)
    wisher.pendown()
    wisher.begin_fill()
    wisher.right(90)
    wisher.forward(200)
    wisher.left(90)
    wisher.forward(30)
    wisher.left(90)
    wisher.forward(90)
    wisher.right(90)
    wisher.forward(70)
    wisher.right(90)
    wisher.forward(90)
    wisher.left(90)
    wisher.forward(30)
    wisher.left(90)
    wisher.forward(200)
    wisher.left(90)
    wisher.forward(30)
    wisher.left(90)
    wisher.forward(90)
    wisher.right(90)
    wisher.forward(70)
    wisher.right(90)
    wisher.forward(90)
    wisher.left(90)
    wisher.forward(30)
    wisher.stamp()
    wisher.end_fill()

    #D
    wisher.penup()
    wisher.goto(-110, -200)
    wisher.pendown()
    wisher.begin_fill()
    wisher.left(100)
    wisher.forward(210)
    wisher.penup()
    wisher.goto(-110, -200)
    wisher.pendown()
    wisher.right(90)
    wisher.forward(20)
    wisher.circle(100, 180)
    wisher.forward(20)
    wisher.end_fill()
    wisher.color('red', 'white')
    wisher.right(180)
    wisher.penup()
    wisher.goto(-90, -170)
    wisher.left(90)
    wisher.pendown()
    wisher.begin_fill()
    wisher.forward(150)
    wisher.penup()
    wisher.goto(-100, -170)
    wisher.pendown()
    wisher.right(90)
    wisher.forward(10)
    wisher.circle(75, 180)
    wisher.forward(10)
    wisher.end_fill()

    #A
    wisher.penup()
    wisher.goto(-70, -200)
    wisher.pendown()
    wisher.color('red', 'lime')
    wisher.begin_fill()
    wisher.right(115)
    wisher.forward(200)
    wisher.right(125)
    wisher.forward(200)
    wisher.right(115)
    wisher.forward(30)
    wisher.right(45)
    wisher.forward(30)
    wisher.left(42)
    wisher.forward(90)
    wisher.left(45)
    wisher.forward(30)
    wisher.right(45)
    wisher.forward(20)
    wisher.end_fill()

    wisher.penup()
    wisher.goto(-25, -155)
    wisher.pendown()
    wisher.color('red', 'white')
    wisher.begin_fill()
    wisher.right(120)
    for x in range(3):
        wisher.forward(90)
        wisher.right(120)
    wisher.end_fill()

    #Y
    wisher.right(30)
    wisher.penup()
    wisher.goto(60, -150)
    wisher.pendown()
    wisher.color('red', 'lime')
    wisher.begin_fill()
    wisher.left(10)
    wisher.forward(95)
    wisher.left(90)
    wisher.forward(95)
    wisher.right(90)
    wisher.forward(30)
    wisher.right(90)
    wisher.forward(95)
    wisher.left(90)
    wisher.forward(95)
    wisher.right(90)
    wisher.forward(30)
    wisher.right(90)
    wisher.forward(250)
    wisher.end_fill()


birthday_wish()
screen.exitonclick()